- id: doi:10.1093/molbev/msae007
  title: Ecological diversification in an adaptive radiation of plants':' the role of de novo mutation and introgression
  publisher: Molecular Biology and Evolution
  type: paper
  description: Parallel loss of blue pigments in hummingbird-pollinated flowers
  date: 2024-01-17
  image: images/research_insets/mbe-2024.jpeg
  buttons:
    - type: source
      text: Manuscript Source
      link: https://academic.oup.com/mbe/article/41/1/msae007/7564791
  tags:
    - pollination syndrome
    - phylogenomics
    - parallel evolution


- id: doi:10.1002/ajb2.16118
  title: Testing hypotheses of hybrid taxon formation in the shrubby beardtongues (Penstemon subgenus Dasanthera)
  publisher: American Journal of Botany
  type: paper
  description: Investigating hybrid speciation in the shrubby Penstemons
  date: 2023-01-24
  image: images/research_insets/ajb-2023.jpg
  buttons:
    - type: source
      text: Manuscript Source
      link: https://bsapubs.onlinelibrary.wiley.com/doi/full/10.1002/ajb2.16118
  tags:
    - hybridization
    - phylogenetics
    - RAD-seq


- id: doi:10.1111/mec.15992
  title: Phylogeographic analysis of shrubby beardtongues reveals range expansions during the Last Glacial Maximum and implicates the Klamath Mountains as a hotspot for hybridization
  publisher: Molecular Ecology
  type: paper
  description: Phylogeography of the shrubby Penstemons
  date: 2021-05-20
  image: images/research_insets/molec-2021.jpg
  buttons:
    - type: source
      text: Manuscript Source
      link: https://onlinelibrary.wiley.com/doi/abs/10.1111/mec.15992
  tags:
    - phylogeography
    - hybridization
    - RAD-seq


- id: doi:10.3159/TORREY-D-19-00036.1
  title: Little genetic distinction between varieties of Pinto Beardtongue (Penstemon bicolor, Plantaginaceae), a rare plant native to the Mojave Desert
  publisher: Journal of the Torrey Botanical Society
  type: paper
  description: Population genetics of a rare species of *Penstemon*
  date: 2020-06-22
  image: https://www.researchgate.net/profile/Benjamin-Stone-7/publication/343475508/figure/fig1/AS:11431281078878314@1660327588106/Locations-of-populations-sampled-in-this-study-Variety-bicolor-populations-appear-in_W640.jpg
  buttons:
    - type: source
      text: Manuscript Source
      link: https://bioone.org/journals/the-journal-of-the-torrey-botanical-society/volume-147/issue-2/TORREY-D-19-00036.1/----Custom-HTML----Little/10.3159/TORREY-D-19-00036.1.short
  tags:
    - population genetics
    - SSRs


- id: doi:10.21425/F5FBG45377
  title: Does habitat stability structure intraspecific genetic diversity? It’s complicated...
  publisher: Frontiers of Biogeography
  type: paper
  description: Comparative phylogeography of species in the southeastern United States
  date: 2020-04-01
  image: https://www.jaminwieringa.com/uploads/8/7/7/8/87785926/phylogeo-pic_orig.png
  buttons:
    - type: source
      text: Manuscript Source
      link: https://escholarship.org/uc/item/4jg256x0
  tags:
    - phylogeography


- id: doi:10.1007/s10592-019-01204-1
  title: Genetic diversity and population structure in Cary’s Beardtongue Penstemon caryi (Plantaginaceae), a rare plant endemic to the eastern Rocky Mountains of Wyoming and Montana
  publisher: Conservation Genetics
  type: paper
  description: Conservation study of the narrowly endemic *Penstemon caryi* 
  date: 2019-06-29
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs10592-019-01204-1/MediaObjects/10592_2019_1204_Fig1_HTML.png?as=webp
  buttons:
    - type: source
      text: Manuscript Source
      link: https://link.springer.com/article/10.1007/s10592-019-01204-1
  tags:
    - conservation biology
    - AFLPs
    - SSRs